USE [pe_db_complaintMGT]
GO
/****** Object:  Table [dbo].[tbl_MeterParameters]    Script Date: 11/25/2025 9:41:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_MeterParameters](
	[ParameterID] [int] NOT NULL,
	[MeterMasterID] [int] NULL,
	[ParameterPhaseID] [int] NULL,
	[MeterParaMeterMapping] [varchar](50) NULL,
	[DataType] [varchar](50) NULL,
	[Addresss] [int] NULL,
	[Remarks] [varchar](255) NULL,
	[CreateDate] [datetime] NULL,
	[UpdateDate] [datetime] NULL,
	[CreateBy] [varchar](50) NULL,
	[UpdateBy] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ParameterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (1, 1, 1, N'P1', N'varchar', NULL, N'MeterType', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (2, 1, 1, N'P2', N'varchar', NULL, N'MeterName', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (3, 1, 2, N'P3', N'float', 40117, N'Power Factor Avg', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (4, 1, 3, N'P4', N'float', 40103, N'Load R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (5, 1, 3, N'P5', N'float', 40143, N'Line to neutral R Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (6, 1, 3, N'P6', N'float', 40151, N'Current R Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (7, 1, 4, N'P7', N'float', 40105, N'Load Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (8, 1, 4, N'P8', N'float', 40145, N'Line to neutral Y Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (9, 1, 4, N'P9', N'float', 40153, N'Curent Y Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (10, 1, 5, N'P10', N'float', 40107, N'Load B Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (11, 1, 5, N'P11', N'float', 40147, N'Line to neutral B Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (12, 1, 5, N'P12', N'float', 40155, N'Curent B Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (13, 1, 2, N'P13', N'float', 400159, N'Wh Received (Cumulative Energy (total of 3 phase)  KWAH)', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (14, 1, 2, N'P14', N'Long Inverse', 400217, N'Load Hours Received or RunHrs', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (15, 1, 2, N'P15', N'float', 40101, N'Watts Total (Total Load (R+Y+B phase))', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (16, 1, 2, N'P16', N'float', 40141, N'Line to neutral', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (17, 1, 2, N'P17', N'float', 40149, N'Avg Current', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (18, 1, 2, N'P18', N'float', 400161, N'Vah Received (Cumulative Energy (total of 3 phase)  KVAH)', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (19, 1, 2, N'P19', N'Long Inverse', 400229, N'On_hours', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (20, 1, 3, N'P20', N'float', 400243, N'kWh received û R Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (21, 1, 4, N'P21', N'float', 400245, N'kWh received û Y Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (22, 1, 5, N'P22', N'float', 400247, N'kWh received û B Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (23, 1, 3, N'P23', N'float', 400249, N'kVAh received û R Phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (24, 1, 4, N'P24', N'float', 400251, N'kVAh received û Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (25, 1, 5, N'P25', N'float', 400253, N'kVAh received û B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (26, 2, 1, N'P1', N'varchar', NULL, N'MeterType', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (27, 2, 1, N'P2', N'varchar', NULL, N'MeterName', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (28, 2, 2, N'P3', N'float', 40159, N'Import Energy  [Wh]', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (29, 2, 3, N'P4', N'float', 40103, N'Watts R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (30, 2, 4, N'P5', N'float', 40105, N'Watts Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (31, 2, 5, N'P6', N'float', 40107, N'Watts B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (32, 2, 2, N'P7', N'Long Inverse', 40217, N'Import Load Hour', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (33, 2, 2, N'P8', N'float', 40101, N'Watts Total', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (34, 2, 2, N'P9', N'float', 40353, N'True PF Average', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (35, 2, 2, N'P10', N'float', 40141, N'VLN average', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (36, 2, 3, N'P11', N'float', 40143, N'V R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (37, 2, 4, N'P12', N'float', 40145, N'V Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (38, 2, 5, N'P13', N'float', 40147, N'V B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (39, 2, 2, N'P14', N'float', 40149, N'Current average', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (40, 2, 3, N'P15', N'float', 40151, N'Current R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (41, 2, 4, N'P16', N'float', 40153, N'Current Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (42, 2, 5, N'P17', N'float', 40155, N'Current B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (43, 2, 2, N'P18', N'float', 40161, N'Import Energy  [VAh]', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (44, 2, 3, N'P19', N'float', 40243, N'Import Energy EB [Wh] R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (45, 2, 4, N'P20', N'float', 40245, N'Import Energy EB [Wh] Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (46, 2, 5, N'P21', N'float', 40247, N'Import Energy EB [Wh] B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (47, 2, 3, N'P22', N'float', 40249, N'Import Energy EB [VAh] R phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (48, 2, 4, N'P23', N'float', 40251, N'Import Energy EB [VAh] Y phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
INSERT [dbo].[tbl_MeterParameters] ([ParameterID], [MeterMasterID], [ParameterPhaseID], [MeterParaMeterMapping], [DataType], [Addresss], [Remarks], [CreateDate], [UpdateDate], [CreateBy], [UpdateBy]) VALUES (49, 2, 5, N'P24', N'float', 40253, N'Import Energy EB [VAh] B phase', CAST(N'2025-10-01T09:10:00.000' AS DateTime), NULL, N'adminhk', N'NULL')
GO
ALTER TABLE [dbo].[tbl_MeterParameters]  WITH NOCHECK ADD  CONSTRAINT [FK_tbl_MeterParameters_tbl_MeterMaster] FOREIGN KEY([MeterMasterID])
REFERENCES [dbo].[tbl_MeterMaster] ([MeterMasterID])
GO
ALTER TABLE [dbo].[tbl_MeterParameters] CHECK CONSTRAINT [FK_tbl_MeterParameters_tbl_MeterMaster]
GO
ALTER TABLE [dbo].[tbl_MeterParameters]  WITH NOCHECK ADD  CONSTRAINT [FK_tbl_MeterParameters_tbl_ParameterPhaseMaster] FOREIGN KEY([ParameterPhaseID])
REFERENCES [dbo].[tbl_ParameterPhaseMaster] ([ParameterPhaseID])
GO
ALTER TABLE [dbo].[tbl_MeterParameters] CHECK CONSTRAINT [FK_tbl_MeterParameters_tbl_ParameterPhaseMaster]
GO
